### ISSUE TITLE
[FEATURE REQUEST] License Plate

### ISSUE THREAD

**Issue by hyanmandian** [brazilian-utils/brazilian-utils#112]
I really don't know if we have some rules to create Mercosul/Brazilian license plate, but I think that we should keep support for both (after 2024 we can drop Brazilian support since Brazil will only use Mercosul format).

**Comment by igortupini** [comment]
A generator validator is fairly simple to implement and would be great to have. Today I'm using my own helpers to validate and generate Brazilian/Mercosul license plate.

**Comment by hyanmandian** [comment]
closed by @marceloabk
