### ISSUE TITLE
Add phone validation

### ISSUE THREAD

**Issue by hyanmandian** [brazilian-utils/brazilian-utils#16]

**Comment by emersonlaurentino** [comment]
would be with `dialing code` of the country and state? plus the digit 9?

examples: `+55 11 9 1122-3344`

**Comment by hyanmandian** [comment]
I think that for brazilian we just need to check the length, like this one https://github.com/brazilian-utils/brazilian-utils/tree/master/packages/is-valid-cep

**Comment by emersonlaurentino** [comment]
I did an implementation, I'll send a PR.

**Comment by emersonlaurentino** [comment]
@hyanmandian can u make a review in #27?

**Comment by hyanmandian** [comment]
Yes man! Sorry for the delay :( I think that @lucassveloso can check this and publish your package
