### ISSUE TITLE
Add CEP validation

### ISSUE THREAD

**Issue by hyanmandian** [brazilian-utils/brazilian-utils#17]

**Comment by luiscoms** [comment]
Just the format? 

    999999-999

**Comment by hyanmandian** [comment]
Yes, but I think that you should handle with or without mask like other pakages

**Comment by luiscoms** [comment]
I guess that we could use this project for example

https://github.com/luiscoms/jquery.maskedinput

**Comment by hyanmandian** [comment]
Actually, the idea is basically to check if the CEP is valid

**Comment by mikaelhadler** [comment]
@hyanmandian this issue it's closed no ?

**Comment by hyanmandian** [comment]
@mikaelhadler yes, thanks!
