### ISSUE TITLE
Adicionar gerador de CPF/CNPJ

### ISSUE THREAD

**Issue by rdsedmundo** [brazilian-utils/brazilian-utils#223]
Útil para testes.

**Comment by hyanmandian** [comment]
Olá @rdsedmundo tudo bem? Já possuimos esses geradores, você pode conferir aqui: [CPF](https://github.com/brazilian-utils/brazilian-utils/blob/main/src/utilities/cpf/index.ts#L52) e [CNPJ](https://github.com/brazilian-utils/brazilian-utils/blob/main/src/utilities/cnpj/index.ts#L57).

Pelo que vi, não adicionamos eles na documentação oficial, mas caso queira nos ajudar, sinta-se a vontade para contribuir e adicona-los a nossa documentação.

**Comment by tbfreitas** [comment]
Olá @hyanmandian , gostaria de fazer essa documentação.
Ou vocês já estão trabalhando sobre esse aspecto ?

**Comment by hyanmandian** [comment]
@tbfreitas sinta-se a vontade! seria incrivel termos a sua contribuição!

**Comment by hyanmandian** [comment]
Resolvido #226

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
