### ISSUE TITLE
CONTRIBUTING.md not have information how to create a new package

### ISSUE THREAD

**Issue by mikaelhadler** [brazilian-utils/brazilian-utils#23]
**Is your feature request related to a problem? Please describe it.**
I fork this project, but, i don't see any information how to create a new package with a correct structure.

**Describe the solution you'd like**
Just incrise information in CONTRIBUTING.md how to create a correct structure.

**Comment by andreoav** [comment]
I'll take some time to improve our CONTRIBUTING.md file.

;)

**Comment by hyanmandian** [comment]
In v1 (current) we simplify the project structure and I think we don't have this issue anymore.
