### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by hyanmandian** [brazilian-utils/brazilian-utils#29]

**Comment by hyanmandian** [comment]
Maybe we can use just type definitions to avoid rewriting all packages... What do you think about it?

**Comment by andreoav** [comment]
Our packages are small pieces of code.

Rewrting them with Typescript is not a bad idea.

**Comment by VitorLuizC** [comment]
@aputhin will you rewrite all packages or we can do it one by one? Either way, I would like to help you with it.

**Comment by vhfmag** [comment]
Tentei minha sorte com essa issue :grimacing:

**Comment by vhfmag** [comment]
I tried my luck with the Typescript rewrite in #33. Hope it helps!

**Comment by matheusgrieger** [comment]
Can someone help? Even though the whole project is written in TS, when importing a specific package (such as `@brazilian-utils/is-valid-cpf`), the compiler still complains about not finding a type definitions file. Do I need to do something else than just installing and importing?

Thanks for the amazing work!

**Comment by vhfmag** [comment]
I'm taking a look at it, @matheusgrieger. We're probably either not generating the definitions file or not pointing to it from package.json.

**Comment by vhfmag** [comment]
As it turns out, both :neutral_face:

**Comment by vhfmag** [comment]
I will be looking at it tomorrow and will send a PR

**Comment by vhfmag** [comment]
@matheusgrieger, see #37 and #38

**Comment by matheusgrieger** [comment]
@vhfmag thanks a lot for that!

**Comment by ramonornela** [comment]
@vhfmag some planning to publish new version in the npm?

**Comment by hyanmandian** [comment]
Yes @ramonornela , in the next release we going to publish next version of brazilian-utils. You can check our work in #63 . Fell free to contribute and help us to migrate all missing packages to new structure.
