### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by rochapablo** [brazilian-utils/brazilian-utils#40]
**Describe the bug**

```
Could not find a declaration file for module '@brazilian-utils/is-valid-cpf'. 'node_modules/@brazilian-utils/is-valid-cpf/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/brazilian-utils__is-valid-cpf` if it exists or add a new declaration (.d.ts) file containing `declare module '@brazilian-utils/is-valid-cpf';`ts(7016)
```

Same with

```
import isValidCnpj from '@brazilian-utils/is-valid-cnpj';
or
import { isValidCpf, isValidCnpj } from '@brazilian-utils/validators';
```

**To Reproduce**
1. `npm install @brazilian-utils/is-valid-cpf --save`
2. `import isValidCpf from '@brazilian-utils/is-valid-cpf';`
3. See error

**Expected behavior**
It should import with no problem

**Comment by vhfmag** [comment]
It seems there hasn't been a deploy since #38. I thought there would have been a `types` field in `package.json` pointing to a file that didn't exist, but the field itself is missing (https://unpkg.com/@brazilian-utils/is-valid-cnpj/package.json). Any idea of what happened? @hyanmandian @andreoav

**Comment by hyanmandian** [comment]
I really don't know what happened :( but @andreoav started to rewrite the architecture ( #36) and this problem probably will solve with that rewrite.

**Comment by pedroSoaresll** [comment]
try delete your node_modules folder and reinstall. to me worked normally. strange :/

**Comment by pedroSoaresll** [comment]
hmm if you are using with typescript, i don't know if this library have a @types, configure your tsconfig.json to allow pass libraries without @types defined

**Comment by hyanmandian** [comment]
we started working in refactoring of the entire project to solve issues like that, maybe in the next weeks we'll finish

**Comment by pedroSoaresll** [comment]
Hey @hyanmandian, how do you think to solve this problem?

**Comment by hyanmandian** [comment]
Just adding types property on package.json. Probably before I starting the refactoring of the entire project, I will publish a new version of each package with types

**Comment by hyanmandian** [comment]
Hey, we publish our first RC of the next version of our package today :D.  Can you check if our typings are exported correctly?

https://www.npmjs.com/package/@brazilian-utils/brazilian-utils

**Comment by hyanmandian** [comment]
I did this example to show typings working in v1 version (current) https://codesandbox.io/s/brazilian-utils-typescript-example-6fhmt
