### ISSUE TITLE
@brazilian-utils/format-boleto unavailable on NPM

### ISSUE THREAD

**Issue by thebinaryfelix** [brazilian-utils/brazilian-utils#50]
**Describe the bug**
Package format-boleto not being found on NPM to be installed on project.

**To Reproduce**
1. `npm install @brazilian-utils/format-boleto --save`
2. See error

**Expected behavior**
Package should be installed without problems.

**Additional context**
Package is not being found on the NPM registry.

**Comment by hyanmandian** [comment]
You right, sorry for that :( we forget to publish this package. We will publish this package ASAP.

**Comment by thebinaryfelix** [comment]
Thanks!

**Comment by hyanmandian** [comment]
Done! Now you can use `@brazilian-utils/format-boleto`.

A little disclaimer... Now we are working on a big refactoring of the entire library and this package will split into 3 packages: `@brazilian-utils/format-boleto-bancario` that formats only boleto bancário, `@brazilian-utils/format-titulo-convenio` that formats only título and convênio and  `@brazilian-utils/format-boleto-titulo-convenio` (probably with another name HAhAHHA) that formats boleto báncario and títulos e convênios.

I don't know if this is the best approach to do that, but I think this way we separate the logic and make it easier to maintain.

You can follow our changes (and contribute if you like) on `refactoring-v2` branch ( https://github.com/brazilian-utils/brazilian-utils/tree/refactoring-v2).

Thanks!
