### ISSUE TITLE
Add boleto validation

### ISSUE THREAD

**Issue by PatriciaDurand** [brazilian-utils/brazilian-utils#6]

**Comment by rodineijf** [comment]
Maybe this can help: https://cmsportal.febraban.org.br/Arquivos/documentos/PDF/Layout%20-%20C%C3%B3digo%20de%20Barras%20-%20Vers%C3%A3o%205%20-%2001_08_2016.pdf

**Comment by mikaelhadler** [comment]
Hey @PatriciaDurand do you have a description for this task? I need more information for work in this item.

**Comment by rodineijf** [comment]
Hi @mikaelhadler i'm already started this. Only don't know how to push this card to "in progress';

**Comment by emersonlaurentino** [comment]
Can this issue be closed? once resolved at #26

**Comment by lucassveloso** [comment]
Closed by #26
