### ISSUE TITLE
Brazilian cities

### ISSUE THREAD

**Issue by arantespp** [brazilian-utils/brazilian-utils#87]
Related to #82, is it a good idea to create a method that returns all Brazilian cities?

We may create a script that gets all cities from [IBGE API](https://servicodados.ibge.gov.br/api/docs/localidades?versao=1#api-Microrregioes-estadosUFMicrorregioesGet), for instance, and saves them in a JSON. This way is easier to update cities.

**Comment by hyanmandian** [comment]
Good idea! We just need to test if our tree shaking works as expected because if don't, we will have an issue related with our bundle size :(

**Comment by arantespp** [comment]
I see. I'm testing here the size of the JSON and saving only the cities name will increase 100k of the bundle size. Is this a reasonable value when importing `getCities`? 

Also, how about we create an SDK for IBGE API inside brazilian-utils?

**Comment by hyanmandian** [comment]
Yes, I think the size is not a problem when just increase this size when importing `getCities`, we just need to test if this happens. About IBGE API, I think that's is out of our scope :( 

Hey @andreoav what you think about that?

**Comment by arantespp** [comment]
Great! I'll submit a PR with `getCities` to check if the three shaking works fine.

**Comment by hyanmandian** [comment]
Hello @arantespp, you need some help to that? I'm really liked your idea about `getCities`.

**Comment by arantespp** [comment]
@hyanmandian Hey! I'm so sorry, the last days were very busy. Now I get some time and I'll work in the first version of `getCities`. I'll create a PR just for testing the bundle size, ok? If it works, we think about creating a filter for states.

**Comment by hyanmandian** [comment]
Closed by #92
